---
title: "Final"
author: "Manuel Vazquez, Errol Kaylor, Tingyu Zou"
date: "2/25/2022"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tmap)
library(edld652)
library(tidyverse)
library(skimr)
library(gghighlight)
list_datasets()
library(arrow)
library(here)
library(rio)
library(ggrepel)
library(tigris)
library(leaflet)
library(flexdashboard)
```


```{r data_setup}
list_datasets()
district_math_participation <- as_tibble(get_data("EDFacts_math_achievement_lea_2010_2019"))
district_math_achievement <- as_tibble(get_data("EDFacts_math_participation_lea_2013_2019"))
district_reading_participation <- as_tibble(get_data("EDFacts_rla_participation_lea_2013_2019"))
district_reading_achievement <- as_tibble(get_data("EDFacts_rla_achievement_lea_2010_2019"))
district_ccd_fiscal_2012 <- as_tibble(get_data("NCES_CCD_fiscal_district_2012"))
district_directory <- as_tibble(get_data("NCES_CCD_nonfiscal_district_2017_2021_directory"))
district_el <- as_tibble(get_data("NCES_CCD_nonfiscal_district_2017_2021_english_learners"))
district_membership <- as_tibble(get_data("NCES_CCD_nonfiscal_district_2017_2021_membership"))
head(district_el)
district_membership <- as_tibble(read_parquet(here( "district-membership-17-21.parquet")))
#school_membership <- as_tibble(read_parquet(here("school-membership-17-21.parquet")))

#head(district_reading_participation)

#take the above files, and filter to oregon data
or_district_math_achievement <- district_math_achievement %>% 
  filter(STNAM == "OREGON")
or_district_math_participation <- district_math_participation %>% 
  filter(STNAM == "OREGON")
or_district_rla_achievement <- district_reading_achievement %>% 
  filter(STNAM == "OREGON")
or_district_rla_participation <- district_reading_participation %>% 
  filter(STNAM == "OREGON")
or_district_fiscal_2012 <- district_ccd_fiscal_2012 %>% 
  filter(STNAME == "Oregon")
or_district_directory <- district_directory %>% 
  filter(STATENAME == "OREGON")
or_district_el <- district_el %>% 
  filter(STATENAME == "OREGON") %>% 
  select(LEAID,
         SCHOOL_YEAR,
         LEP_COUNT)

or_district_membership <- district_membership %>% 
  filter(STATENAME == "OREGON")

or_district_el_directory <- 
  left_join(or_district_directory,
            or_district_el,
            by="LEAID")

full_dataset <- left_join(or_district_el_directory,
                          or_district_rla_achievement,
                          by="LEAID") %>% 
  left_join(or_district_rla_participation,
            by="LEAID")

or_district_data <- school_districts(state=41)

pal <- colorNumeric(
  palette = "Blues",
  domain = full_dataset$LEP_COUNT)

leaflet(or_district_data) %>%
  addProviderTiles("CartoDB.Positron") %>% 
  addPolygons(color = ~pal(full_dataset$LEP_COUNT),
              weight = 0.5,
              fillOpacity = 1) 
```

# Who Knows!

Background {.sidebar}
---------------------------------------
Some words here!

Column {.tabset .tabset-fade data-width = 600}
---------------------------------------------------------------------
### About

```{r}
pal <- colorNumeric(
  palette = "Blues",
  domain = full_dataset$LEP_COUNT)

leaflet(or_district_data) %>%
  addProviderTiles("CartoDB.Positron") %>% 
  addPolygons(color = ~pal(full_dataset$LEP_COUNT),
              weight = 0.5,
              fillOpacity = 1) 
```




```{r }
dli <- import(here("data","districts_dli.xlsx")) %>%
  janitor::clean_names() %>%
  mutate(leaid = as.character(leaid))

or_el <- or_district_el %>%
  filter(SCHOOL_YEAR == "2018-2019") %>%
  select(LEAID, LEP_COUNT) %>%
  janitor::clean_names()

or_enroll_white <- or_district_membership %>%
  filter(SCHOOL_YEAR == "2018-2019" & 
           GRADE == "No Category Codes" &
           RACE_ETHNICITY == "White") %>%
  group_by(LEAID) %>%
  summarize(student_white_count = sum(STUDENT_COUNT))


or_enroll_total <- or_district_membership %>%
  filter(SCHOOL_YEAR == "2018-2019" & 
           GRADE == "No Category Codes" &
           RACE_ETHNICITY == "No Category Codes" & 
           SEX == "No Category Codes" &
         TOTAL_INDICATOR == "Education Unit Total" &
           STUDENT_COUNT > 0 &
           !is.na(STUDENT_COUNT) ) %>%
  left_join(or_enroll_white, by = "LEAID") %>%
  mutate(white_pct = (student_white_count/STUDENT_COUNT)*100) %>%
  janitor::clean_names() %>%
  left_join(dli,by="leaid") %>%
  left_join(or_el,by = "leaid") %>%
  select(leaid,lea_name,student_count,student_white_count,white_pct,schools_dli, lep_count) %>%
  mutate(schools_dli = ifelse(is.na(schools_dli),0,schools_dli),
         el_pct = (lep_count/student_count)*100,
         dli_cat = case_when(schools_dli == 0 ~ "0 schools",
                             schools_dli > 0 & schools_dli < 3 ~"1-2 schools",
                             schools_dli > 2 & schools_dli < 6 ~ "3-5 schools",
                             schools_dli > 3 ~"More than 5 schools"
                             ))
  


```

### About

## Creating a plot that visualizes DLI concentration by white and EL concentration in Oregon

```{r }

or_enroll_total%>%
  ggplot(aes(x = el_pct, y=white_pct)) +
  geom_point(aes(size = lep_count), color = "grey80") +
  geom_point(data = filter(or_enroll_total,schools_dli > 0 & !is.na(dli_cat)),
             aes(el_pct,y = white_pct, size = lep_count, color = as.factor(dli_cat))) +
  geom_text_repel(data = filter(or_enroll_total,el_pct > 10 & lep_count > 750 & schools_dli == 0),
                  aes(label = lea_name), min.segment.length = 0, box.padding = 1.25) +
  scale_size_continuous(
    name = "Number of EL students",
    breaks = c(50,100,500,750, 1000)) +
  xlim(0,35) +
# create the quadrants
  geom_segment(aes(x = 35, y = 0, xend = 35, yend = 100)) +
  geom_segment(aes(x = 0, y = 0, xend = 0, yend = 100)) +
  geom_segment(aes(x = 0, y = 0, xend = 35, yend = 0)) +
  geom_segment(aes(x = 0, y = 60, xend = 35, yend = 60)) +
  geom_segment(aes(x = 10, y = 0, xend = 10, yend = 100)) +
  geom_segment(aes(x = 0, y = 100, xend = 35, yend = 100)) +
  # quadrant labels
  annotate("text", x = 5, y = 95, alpha = 0.35, label = "High White, Low EL Districts") +
  annotate("text", x = 20, y = 95, alpha = 0.35, label = " ") +
  annotate("text", x = 20, y = 15, alpha = 0.35, label = "Low White, High EL Districts\n\ (Candiates for DLI programs)") +
  annotate("text", x = 5, y = 15, alpha = 0.35, label = " ") +
  theme_minimal() +
  labs(title = "A high concentration of Oregon districts with DLI programs are in predominantly white districts",
       y = "Percent white", 
       x = "Percent EL of total enrollment")
  


```

```{r-achievement}
s <- get_data("EDFacts_rla_achievement_lea_2010_2019")
get_documentation("EDFacts_rla_achievement_lea_2010_2019")
ach <- filter(s,STNAM=="OREGON") %>% 
  drop_na(LEP_RLA00PCTPROF)

ach2 <- ach %>% 
  rename(leaid=LEAID)

FinalDF <- left_join(or_enroll_total,ach2,by="leaid") %>% 
  drop_na(LEP_RLA00PCTPROF)

#remove rows that are privacy protected
Final <- filter(FinalDF,LEP_RLA00PCTPROF!="PS",
                LEP_RLA00PCTPROF!="GE50",
                LEP_RLA00PCTPROF!="LT50",
                LEP_RLA00PCTPROF!="LE20")



ggplot(Final, aes(el_pct, white_pct)+
         geom_point(color = "gray70")+
         geom_text_repel(aes(label = LEP_RLA00PCTPROF))+
         theme_minimal() +
         labs(title = "Destrict and Achievement", 
              y = "Percent white", 
              x = "Percent EL of total enrollment")
       
```

