---
title: "RQ 1 and 2"
author: "Manuel Vazquez Cano"
date: "2/20/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library("rio")
library("here")
library("tidyverse")
library("edld652")
```

## 

```{r }
dli <- import(here("data","districts_dli.xlsx"))
el <- get_data("NCES_CCD_nonfiscal_district_2017_2021_english_learners") %>%
  filter(ST == "OR") %>% 
  filter(SCHOOL_YEAR == "2018-2019") %>%
  select(LEAID,LEP_COUNT)

enrollment <- get_data("NCES_CCD_nonfiscal_district_2017_2021_membership") 
arrow::write_parquet(enrollment, here("data"))


enroll <- enrollment %>% 
  filter(ST == "OR") %>%
  filter(SCHOOL_YEAR == "2018-2019")




```

# Merging the data

```{ r}

```


## Creating a plot

```{r }

data %>%
  ggplot(aes(x=pct_white, y = pct_frpl, color = "dli_group" , size = "el_enrollment")) +
  geom_point() +
# create the quadrants
  geom_segment(aes(x = 100, y = 0, xend = 10, yend = 100)) +
  geom_segment(aes(x = 0, y = 0, xend = 0, yend = 100)) +
  geom_segment(aes(x = 0, y = 0, xend = 100, yend = 0)) +
  geom_segment(aes(x = 0, y = 5, xend = 100, yend = 50)) +
  geom_segment(aes(x = 50, y = 0, xend = 50, yend = 100)) +
  geom_segment(aes(x = 0, y = 100, xend = 100, yend = 100)) +
  


```


