---
title: "updated codes for RQ3"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#library(tmap)
library(edld652)
library(tidyverse)
library(skimr)
library(gghighlight)
#list_datasets()
library(arrow)
library(here)
library(rio)
library(ggrepel)
library(tigris)
library(leaflet)
```

```{r previous_version_for_RQ3}
# s <- get_data("EDFacts_rla_achievement_lea_2010_2019")
# get_documentation("EDFacts_rla_achievement_lea_2010_2019")
# ach <- filter(s,STNAM=="OREGON")
# 
# 
# ggplot(ach,aes(fct_reorder(LEAID,ALL_RLA00NUMVALID),ALL_RLA00NUMVALID,fill=LEP_RLA00NUMVALID))+
#   geom_col()+
#   coord_flip()+
#   theme_classic()
#    
#           
# ggplot(ach,aes(fct_reorder(LEAID,ALL_RLA00NUMVALID),ALL_RLA00NUMVALID))+
#   geom_col(fill="#00ff7b")+
#   coord_flip()+
#   theme_classic() 
# 
# 
# ggplot(ach,aes(fct_reorder(LEAID,LEP_RLA00NUMVALID),LEP_RLA00NUMVALID))+
#   geom_col(fill="#00ffe1")+
#   coord_flip()+
#   theme_classic()   
#   
# 
# ggplot(ach,aes(LEAID,LEP_RLA00NUMVALID))+
#   geom_col(fill="#00ffe1")+
#   theme_classic() 

```



```{r data_setup}
# district_math_participation <- as_tibble(get_data("EDFacts_math_achievement_lea_2010_2019"))
# district_math_achievement <- as_tibble(get_data("EDFacts_math_participation_lea_2013_2019"))
# district_reading_participation <- as_tibble(get_data("EDFacts_rla_participation_lea_2013_2019"))
# district_reading_achievement <- as_tibble(get_data("EDFacts_rla_achievement_lea_2010_2019"))
# district_ccd_fiscal_2012 <- as_tibble(get_data("NCES_CCD_fiscal_district_2012"))
# district_directory <- as_tibble(get_data("NCES_CCD_nonfiscal_district_2017_2021_directory"))
# district_el <- as_tibble(get_data("NCES_CCD_nonfiscal_district_2017_2021_english_learners"))
# district_membership <- as_tibble(get_data("NCES_CCD_nonfiscal_district_2017_2021_membership"))
# head(district_el)
# 
# 
# or_district_math_participation <- as_tibble(get_data("EDFacts_math_achievement_lea_2010_2019")) %>%
#   filter(STNAM == "OREGON")
# 
# or_district_math_achievement <- as_tibble(get_data("EDFacts_math_participation_lea_2013_2019")) %>%
#   filter(STNAM == "OREGON")
# 
# or_district_reading_participation <- as_tibble(get_data("EDFacts_rla_participation_lea_2013_2019")) %>%
#   filter(STNAM == "OREGON")
# 
# or_district_reading_achievement <- as_tibble(get_data("EDFacts_rla_achievement_lea_2010_2019")) %>%
#   filter(STNAM == "OREGON")
# 
# or_district_ccd_fiscal_2012 <- as_tibble(get_data("NCES_CCD_fiscal_district_2012")) %>%
#   filter(STNAME == "OREGON")
# 
# or_district_directory <- as_tibble(get_data("NCES_CCD_nonfiscal_district_2017_2021_directory")) %>%
#   filter(STATENAME == "OREGON")
# 
# or_district_el <- as_tibble(get_data("NCES_CCD_nonfiscal_district_2017_2021_english_learners")) %>%
#   filter(STATENAME == "OREGON") %>%
#   select(LEAID,
#          SCHOOL_YEAR,
#          LEP_COUNT)
# district_membership <- as_tibble(get_data("NCES_CCD_nonfiscal_district_2017_2021_membership"))
# 
# 
# or_district_membership <- district_membership %>% 
#    filter(STATENAME == "OREGON")
# 
# or_district_el_directory <- 
#   left_join(or_district_directory,
#             or_district_el,
#             by="LEAID")
# 
# full_dataset <- left_join(or_district_el_directory,
#                           or_district_reading_achievement,
#                           by="LEAID") %>%
#   #mutate(LEAID = as.numeric(LEAID)) %>%
#     left_join(or_district_reading_participation,
#             by="LEAID")
# 
# or_district_data <- school_districts(state=41)
# 
# pal <- colorNumeric(
#   palette = "Blues",
#   domain = full_dataset$LEP_COUNT)
# 
# leaflet(or_district_data) %>%
#   addProviderTiles("CartoDB.Positron") %>% 
#   addPolygons(color = ~pal(full_dataset$LEP_COUNT),
#               weight = 0.5,
#               fillOpacity = 1) 
# ```
# 
# 
# # RQ What is the relationship between concentration of EL students and dual immersion language programs across the US? (Manuel Working on this)
# 
# ```{r }
# #Importing the file that has list of districts with dual language immersion schools in Oregon
# dli <- import(here("data","districts_dli.xlsx")) %>%
#   janitor::clean_names() %>%
#   mutate(leaid = as.character(leaid))
# 
# # Filtering the EL file to only include years 2018-19
# or_el <- or_district_el %>%
#   filter(SCHOOL_YEAR == "2018-2019") %>%
#   select(LEAID, LEP_COUNT) %>%
#   janitor::clean_names()
# 
# # From the membership file, taking the number of White Students
# or_enroll_white <- or_district_membership %>%
#   filter(SCHOOL_YEAR == "2018-2019" & 
#            GRADE == "No Category Codes" &
#            RACE_ETHNICITY == "White") %>%
#   group_by(LEAID) %>%
#   summarize(student_white_count = sum(STUDENT_COUNT))
# 
# # creating the analytic file with necesarry variables, taking the overall enrollment
# # which is represented by the "No category codes" value
# or_enroll_total <- or_district_membership %>%
#   filter(SCHOOL_YEAR == "2018-2019" & 
#            GRADE == "No Category Codes" &
#            RACE_ETHNICITY == "No Category Codes" & 
#            SEX == "No Category Codes" &
#          TOTAL_INDICATOR == "Education Unit Total" &
#            STUDENT_COUNT > 0 &
#            !is.na(STUDENT_COUNT) ) %>%
#   left_join(or_enroll_white, by = "LEAID") %>%
#   mutate(white_pct = (student_white_count/STUDENT_COUNT)*100,
#          students_color_pct = 100 - white_pct) %>%
#   janitor::clean_names() %>%
#   left_join(dli,by="leaid") %>%
#   left_join(or_el,by = "leaid") %>%
#   select(leaid,lea_name,student_count,student_white_count,white_pct,schools_dli, lep_count, students_color_pct) %>%
#   mutate(schools_dli = ifelse(is.na(schools_dli),0,schools_dli),
#          el_pct = (lep_count/student_count)*100,
#          dli_cat = case_when(schools_dli == 0 ~ "0 schools",
#                              schools_dli > 0 & schools_dli < 3 ~"1-2 schools",
#                              schools_dli > 2 & schools_dli < 6 ~ "3-5 schools",
#                              schools_dli > 3 ~"More than 5 schools"
#                              ))
# 
# saveRDS(or_enroll_total, file = "FINALdata.Rds")
# ```
# 
# ## Creating a plot that visualizes DLI concentration by EL and student of color concentration
# 
# ```{r }
# 
# or_enroll_total%>%
#   ggplot(aes(x = el_pct, y=students_color_pct)) +
#   geom_point(aes(size = lep_count), color = "grey80") +
#   geom_point(data = filter(or_enroll_total,schools_dli > 0 & !is.na(dli_cat)),
#              aes(el_pct,y = students_color_pct, 
#                  size = lep_count, 
#                  color = as.factor(dli_cat)),
#              alpha = .7)+
#   geom_text_repel(data = filter(or_enroll_total, lep_count > 750 & schools_dli > 5),
#                   aes(label = lea_name), min.segment.length = 0, box.padding = 1.05) +
#   scale_size_continuous(
#     name = "Number of EL students",
#     breaks = c(100,500, 1000, 2000, 4000, 6000),
#     range = c(1,10)) +
#   colorblindr::scale_color_OkabeIto(
#     name = "Number of DLI schools"
#   ) +
#   xlim(0,35) +
# # create the quadrants
#   geom_segment(aes(x = 35, y = 0, xend = 35, yend = 100)) +
#   geom_segment(aes(x = 0, y = 0, xend = 0, yend = 100)) +
#   geom_segment(aes(x = 0, y = 0, xend = 35, yend = 0)) +
#   geom_segment(aes(x = 0, y = 40, xend = 35, yend = 40)) +
#   geom_segment(aes(x = 10, y = 0, xend = 10, yend = 100)) +
#   geom_segment(aes(x = 0, y = 100, xend = 35, yend = 100)) +
#   # quadrant labels
#   annotate("text", x = 5, y = 5, alpha = 0.35, label = "Low Students of Color &\n\ Low EL Districts") +
#   annotate("text", x = 20, y = 5, alpha = 0.35, label = " ") +
#   annotate("text", x = 20, y = 85, alpha = 0.35, label = "High Students of Color,\n\ High EL Districts\n\ (Candiates for DLI programs)") +
#   annotate("text", x = 5, y = 95, alpha = 0.35, label = " ") +
#   theme_minimal() +
#   theme(panel.border = element_blank(), 
#         panel.grid.major = element_blank(),
#         panel.grid.minor = element_blank()) +
#   labs(title = "Districts with High concentration of EL students have larger DLI programs",
#        subtitle = "Yet, there is a high concentration of DLI programs in predominantly white districts",
#        y = "Percent students of color", 
#        x = "Percent EL of total enrollment",
#        caption = " \n\ Note: DLI = Dual language immersion") 
```

# Research Question 3
# data set up
```{r}
s <- get_data("EDFacts_rla_achievement_lea_2010_2019")
get_documentation("EDFacts_rla_achievement_lea_2010_2019")
ach <- filter(s,STNAM=="OREGON") %>% 
  drop_na(LEP_RLA00PCTPROF)

ach2 <- ach %>% 
  rename(leaid=LEAID)

FinalDF <- left_join(FINALdata,ach2,by="leaid") %>% 
  drop_na(LEP_RLA00PCTPROF)

#remove rows that are privacy protected
Final <- filter(FinalDF,LEP_RLA00PCTPROF!="PS",
                LEP_RLA00PCTPROF!="GE50",
                LEP_RLA00PCTPROF!="LT50",
                LEP_RLA00PCTPROF!="LE20")

saveRDS(Final, file = "DATA.Rds")



Df <- DATA %>%
  mutate(value1 = as.numeric(str_extract(LEP_RLA00PCTPROF, "\\d+")),
      value2 = abs(as.numeric(str_extract(LEP_RLA00PCTPROF, "\\-\\d+"))),
      LEP_prof_read = ifelse(is.na(value2),value1,((value1+value2)/2))) %>%
  select(leaid,lea_name, white_pct,schools_dli,lep_count,students_color_pct,el_pct,dli_cat,LEP_RLA00PCTPROF,value1,value2,LEP_prof_read) %>% 
  mutate(district_name = gsub("SD.*", "", lea_name)) %>% 
  mutate(Dli2=case_when(schools_dli == 0 ~ "absence of DLI programs", dli_cat != 0  ~ "presence of DLI programs"))


saveRDS(Df, file = "Df.Rds")


```


#Visualize RQ3 (the relationship with LEP achievment and districts)
```{r}
# RQ3_1 <- Df %>% 
# ggplot(aes(y=forcats::fct_reorder(district_name,LEP_prof_read),x=LEP_prof_read, color = dli_cat)) +
#   geom_point(aes(size = el_pct), color = "grey80") +
#   geom_point(data = filter(Df,schools_dli > 0 & !is.na(dli_cat)),
#              aes(size = el_pct, 
#                  color = as.factor(dli_cat)),
#                 alpha = .7) + 
#   geom_vline(xintercept =40, linetype = "dashed", alpha = .6) +
#   xlim(25,75) +
#   theme_minimal() +
#   theme(panel.border = element_blank(), 
#         panel.grid.major = element_blank(),
#         axis.text.y = element_text(size = 4),
#         axis.text.x = element_text(size = 6))+
#          labs(title = "Distribution of English learners that scored at or above proficient in Oregon",
#               y = "District Name", 
#               x = "Percentage of English learners that scored at or above proficient",
#               color = "Dual language immersion programs",
#               size="Percent EL of total enrollment")+
#   theme(legend.title = element_text(size = 8))
# 
# 
# 
# RQ3_2 <- Df %>% 
#   group_by(Dli2) %>% 
#   summarise(avarage=mean(LEP_prof_read)) %>%
#   ungroup() %>%
#   ggplot(aes(fct_reorder(Dli2,avarage),avarage))+
#   geom_col(aes(fill = Dli2),alpha = 0.9,width=.3)+
#   theme_minimal()+
#   labs(x = "",
#        y = "Avarage",
#        fill="")+
#   theme(legend.title = element_text(size = 8))+
#   guides(fill = "none")
  
# library(patchwork)
# RQ3_2_small_txt <- RQ3_2 +
#   theme(axis.text.y = element_text(size = 8),
#         text = element_text(size = 8))
# RQ3_1 + inset_element(RQ3_2_small_txt, 0.5, 0.5, 0.8, 0.)
# RQ3_1 + RQ3_2
# 
dli_read <- Df %>%
  group_by(Dli2) %>%
  summarize(mean = mean(LEP_prof_read))

Df %>% 
ggplot(aes(y=forcats::fct_reorder(district_name,LEP_prof_read),x=LEP_prof_read, color = dli_cat)) +
  geom_point(aes(size = el_pct), color = "grey80") +
  geom_point(data = filter(Df,schools_dli > 0 & !is.na(dli_cat)),
             aes(size = el_pct, 
                 color = as.factor(dli_cat)),
                alpha = .7) + 
  geom_vline(xintercept =42, alpha = .6) +
  geom_vline(xintercept =41, linetype = "dashed", color = "#cfcfcf", alpha = .6, size = 1.25) +
  geom_vline(xintercept =44, linetype = "dashed",  color = "#808080", alpha = .6, size = 1.25) +
  xlim(25,75) +
  theme_minimal() +
  theme(panel.border = element_blank(), 
        panel.grid.major = element_blank(),
        axis.text.y = element_text(size = 4 ),
        axis.text.x = element_text(size = 6)) +
  labs(title = "Distribution of English learners that scored at or above proficient in Oregon",
              y = "", 
              x = "Percentage of English learners that scored at or above proficient",
              color = "Dual language immersion programs",
              size="Percent EL of total enrollment")+
  theme(legend.title = element_text(size = 8))

```
